name: Super Linter

on:
  push:
    branches:
      - master # Change this to the branch you want to run Super Linter on
  pull_request:
    branches:
      - master    

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and Install dependencies
        run: |
          npm config set prefix ~/.npm-global
          export PATH=~/.npm-global/bin:$PATH
          npm install -g actionlint  

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DETAILS: detailed

      - name: Check linting results
        run: |
          if [ -f "${GITHUB_WORKSPACE}/linter-report.html" ]; then
            echo "Linting completed successfully."
            echo "You can find the linting report at: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/blob/${GITHUB_SHA}/linter-report.html"
          else
            echo "Linting failed. Check the workflow logs for details."
            exit 1
          fi
   

          
          
     

          
