name: Super Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DETAILS: detailed

      - name: Set Super Linter Status Check
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: 'linter-report.html'  # Adjust this based on the output of Super Linter
          name: Super Linter Report
          tag_name: ${{ github.sha }}
          body: 'Super Linter has completed successfully.'
