name: Super Linter

on:
  push:
    branches:
      - master # Change this to the branch you want to run Super Linter on
  pull_request:
    branches:
      - master    

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install -g actionlint  

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DETAILS: detailed
      - name: Run tests and lint
        run: |
          npm run lint
          npm test
        # Add more checks as needed
        continue-on-error: true # Continue to the next steps even if linting fails

      - name: Check linting results
        run: |
         if ! call C:\ProgramData\chocolatey\bin\actionlint.exe; then
            echo "Linting failed. Exiting..."
            exit 1
         fi
   

          
          
     

          
