#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Super Linter

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - master # Change this to the branch you want to run Super Linter on
  pull_request:
    branches:
      - master    

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v5.6.1
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DETAILS: detailed
          CREATE_LOG_FILE: true
          LOG_FILE: super-linter.log

      - name: Install actionlint
        run: npm install actionlint

      - name: Check linting results
        run: |
          actionlint_path=$(command -v actionlint)
          echo "actionlint_path: $actionlint_path"
          ls -l "$(dirname "$actionlint_path")"
          if [ -n "$actionlint_path" ]; then
            echo "actionlint is installed at: $actionlint_path"
          else
            echo "actionlint not found in PATH"
            exit 1
          fi   
          
