name: Super Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and Install dependencies
        run: |
          npm config set prefix ~/.npm-global
          export PATH=~/.npm-global/bin:$PATH
          npm install -g actionlint  

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DETAILS: detailed

      - name: Run tests and lint
        run: |
          npm run lint
          npm test
        continue-on-error: true # Continue to the next steps even if linting fails

      - name: Debugging - Print PATH
        run: |
          echo "PATH: $PATH"
          echo "Checking if actionlint is installed: $(command -v actionlint)"

      - name: Check if actionlint is installed
        run: |
          if ! type actionlint > /dev/null 2>&1; then
            echo "Actionlint is not installed. Exiting..."
            exit 1
          fi
