name: Super Linter

on:
  push:
    branches:
      - master # Change this to the branch you want to run Super Linter on

jobs:
  super-linter:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: "false"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Set other configurations as needed
