name: MSTest Unit Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v3

    - name: Restore Dependencies
      run: nuget restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run MSTest
      run: |
        nuget install MSTest.TestAdapter -Version 2.2.6 -OutputDirectory testrunner
        nuget install MSTest.TestFramework -Version 2.2.6 -OutputDirectory testrunner
        testrunner/MSTest.TestAdapter.2.2.6/build/net45/MSTest.exe /testcontainer:Your.Tests.dll
